#!/usr/bin/env bash
# Based on https://gist.github.com/codeinthehole/26b37efa67041e1307db

echo "Starting setup..."

# Check for Homebrew, install if we don't have it
if test ! $(which brew); then
    echo "Installing homebrew..."
    ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
fi

# Update homebrew recipes
echo 'Updating brew...'
brew update

# Install Brew packages
echo "Installing brew packages..."
PACKAGES=(
    git
    node
    yarn
    thefuck
    z
)
brew install ${PACKAGES[@]}
brew cleanup

# Install cask apps
echo "Installing cask apps..."
CASKS=(
    # Development
    visual-studio-code
    iterm2
    # Browsers
    google-chrome
    # Gaming
    league-of-legends
)
brew cask install ${CASKS[@]}

# Oh my zsh install
sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

# Install Fonts
echo "Installing fonts..."
brew tap caskroom/fonts
FONTS=(
    font-fira-code
)
brew cask install ${FONTS[@]}

# Install VS Code Extensions
echo 'Installing VS Code extensions...'
EXTENSIONS=(
    christian-kohler.npm-intellisense
    dbaeumer.vscode-eslint
    eamodio.gitlens
    esbenp.prettier-vscode
    ms-vscode.atom-keybindings
    streetsidesoftware.code-spell-checker
)
code --install-extension  ${EXTENSIONS[@]}

# VS Code Settings
echo 'Copying VS Code settings...'
cp vscode_settings.json $HOME/Library/Application\ Support/Code/User/settings.json

# Bash Aliases
less .zshrc >> ~/.zshrc

# Success Message
echo "Setup complete!"
